- name: Install fish, hub, sysstat, fortune-mod, inetutils, pyenv, pkgfile
  become: true
  pacman:
    name:
      - fish
      - sysstat
      - fortune-mod
      - inetutils
      - pyenv
      - pkgfile

- name: Update pkgfile db
  become: true
  command: pkgfile --update

- name: Install fisher, virtualfish, starship, pfetch
  become: true
  become_user: aur_builder
  aur:
    name:
      - fisher
      - starship
      - pfetch
    skip_installed: true
