- import_tasks: arch.yml
  when: ansible_facts['os_family']|lower|replace(' ', '') == 'archlinux'

- import_tasks: fedora.yml
  when: ansible_facts['pkg_mgr'] == 'dnf'

- name: Change shell to fish for current user
  become: true
  user:
    name: "{{ansible_user_id}}"
    shell: /usr/bin/fish

- name: Change root shell to fish
  become: true
  user:
    name: root
    shell: /usr/bin/fish

- name: Import config.fish
  file:
    force: true
    state: link
    src: "{{dotfiles_dir}}/dotfiles/fish/config.fish"
    path: "{{user_config_dir}}/fish/config.fish"

- name: Import starship.toml
  file:
    force: true
    state: link
    src: "{{dotfiles_dir}}/dotfiles/starship.toml"
    path: "{{user_config_dir}}/starship.toml"

- name: Make functions dir
  file:
    state: directory
    path: "{{user_config_dir}}/fish/functions/"

- name: Copy functions
  file:
    force: true
    state: link
    src: "{{item}}"
    dest: "{{user_config_dir}}/fish/functions/{{item | basename}}"
  with_fileglob:
    - "{{dotfiles_dir}}/dotfiles/fish/functions/*.fish"

- name: Set colors
  command: "fish {{dotfiles_dir}}/scripts/set_fish_colors.fish"

- name: Make root config dir
  become: true
  file:
    state: directory
    path: "/root/.config/fish/"

- name: Import root config.fish
  become: true
  file:
    state: link
    force: true
    src: "{{dotfiles_dir}}/dotfiles/fish/root.config.fish"
    path: "/root/.config/fish/config.fish"

- name: Import root starship.toml
  become: true
  file:
    state: link
    force: true
    src: "{{dotfiles_dir}}/dotfiles/starship.toml"
    path: "/root/.config/starship.toml"

- name: Import root functions
  become: true
  file:
    force: true
    state: link
    src: "{{item}}"
    dest: "/root/.config/fish/functions/{{item | basename}}"
  with_fileglob:
    - "{{dotfiles_dir}}/dotfiles/fish/functions/*.fish"
