- name: Import neofetch config
  file:
    state: link
    src: "{{dotfiles_dir}}/dotfiles/neofetch"
    path: "{{user_config_dir}}/neofetch"
    force: true

- name: Remove EndeavourOS theme, if exists
  become: yes
  pacman:
    name: arc-gtk-theme-eos
    state: absent

- name: Install desktop software
  become: yes
  pacman:
    name:
      - discord
      - plank
      - gimp
      - gnome
      - gnome-tweaks
      - arc-gtk-theme
      - neofetch

- name: Install aur software
  become: true
  become_user: aur_builder
  aur:
    name:
      - jetbrains-toolbox
      - numix-square-icon-theme
    skip_installed: true

- name: Enable gdm
  ansible.builtin.systemd:
    name: gdm
    enabled: yes

- name: Link .ideavimrc
  file:
    state: link
    src: "{{dotfiles_dir}}/dotfiles/.ideavimrc"
    path: "{{user_home}}/.ideavimrc"
    force: true
