- name: Import neofetch config
  file:
    state: link
    src: "{{dotfiles_dir}}/dotfiles/neofetch"
    path: "{{user_config_dir}}/neofetch"
    force: true

- name: Install desktop software
  become: yes
  pacman:
    name:
      - hexchat
      - discord
      - slack-desktop
      - plank
      - gimp
      - gnome
      - gnome-tweaks
      - arc-gtk-theme
      - neofetch

- name: Install aur software
  become: true
  become_user: aur_builder
  aur:
    name:
      - jetbrains-toolbox
      - spotify
      - numix-square-icon-theme
    skip_installed: true

- name: Enable gdm
  ansible.builtin.systemd:
    name: gdm
    enabled: yes
